version: '3.3'

networks: 
  nginx-net:
  internal-net:

services:
  apc-api:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - apc-mongo
    networks: 
      - internal-net
      - nginx-net

  apc-mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - internal-net
  
  # mongo_exporter:
  #   image: eses/mongodb_exporter
  #   ports:
  #     - '9216:9216'
  #   command:
  #     - '--mongodb.uri=mongodb://root:secret@mongo:27017'
  #   depends_on:
  #     - apc-mongo
  #     - apc-prometheus
  #   networks: 
  #     - internal-net

  apc-prometheus:
    image : verasthiago/apc-prometheus
    ports:
      - 9090:9090
    networks: 
      - internal-net
      - nginx-net

  apc-grafana:
    image : verasthiago/apc-grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-apc}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-123}
    depends_on:
      - apc-prometheus
    networks: 
      - internal-net
      - nginx-net  

  apc-nginx:
    image : verasthiago/apc-nginx
    ports:
      - 80:80
    environment:
      - HOST=localhost
    networks:
      - nginx-net
    depends_on:
      - apc-api
      - apc-prometheus
      - apc-grafana

  local:
    image: busybox
    depends_on:
      - apc-mongo


