#Quarta tarefa:
#Implemente um painel de monitoração com as métricas do MySQL em sua máquina utilizando Prometheus e Grafana.
#Depois passe o resultado do comando docker ps e o screenshot de um painel com um gráfico de métricas!
#Dica: exporter

global:
  scrape_interval:     1s
  evaluation_interval: 1s

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'rest_api'
    static_configs:
    - targets: ['rest_api:8080']
  
  - job_name: 'mongo_exporter'
    static_configs:
      - targets: ['mongo_exporter:9216']